apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-brrc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-brrc
    app.kubernetes.io/part-of: tkrw-pr712-0075-0013-app
  name: devfile-sample-brrc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-brrc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-brrc
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0013-tenant/tkrw-pr712-0075-0013-app/devfile-sample-brrc@sha256:0507eac247bde8367aa76df83c8c0f6335c97d5cf1587323995c03ba961bedb6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
